<?php
/**
 * Bundled baseline of local backlink prospects for Midland Floors.
 *
 * Cleaned from the operator-supplied research CSV (junk/placeholder rows
 * stripped). Returned as a plain PHP array so there is NO runtime dependency on
 * any external file. MLS_Backlinks seeds mls_backlink_targets from this on first
 * load and via the "Reset to baseline" action.
 *
 * Each row: category, org, url, how_to, paid_free, priority, notes, scores.
 *
 * The "scores" array holds five 1-5 sub-scores (authority, relevance, roi, ease,
 * free) used by MLS_Backlinks to compute a 0-100 ROI-weighted Priority Score. The
 * authority sub-score is overridden by live DataForSEO domain rank when available.
 *
 * @package Midland_Local_SEO
 */

if ( ! defined( "ABSPATH" ) ) {
	exit;
}

return array(
	array(
		'category' => 'Local organizations & community groups',
		'org' => 'DC Chamber of Commerce',
		'url' => 'https://dcchamber.org/membership/',
		'how_to' => 'Join and appear in member directory; sponsorship gives extra mentions.',
		'paid_free' => 'Paid',
		'priority' => 'High authority / Low effort',
		'notes' => 'Apply online; add profile link after approval',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 4, 'ease' => 4, 'free' => 2 ),
	),
	array(
		'category' => 'Local organizations & community groups',
		'org' => 'Greater Washington Board of Trade',
		'url' => 'https://www.bot.org/',
		'how_to' => 'Join GWBoT; members appear in directory and get event exposure.',
		'paid_free' => 'Paid',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 4, 'ease' => 4, 'free' => 2 ),
	),
	array(
		'category' => 'Local organizations & community groups',
		'org' => 'Greater Washington Hispanic Chamber of Commerce (GWHCC)',
		'url' => 'https://www.gwhcc.org/sponsorships.html',
		'how_to' => 'Sponsor signature events; contact listed on page.',
		'paid_free' => 'Paid',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 4, 'roi' => 3, 'ease' => 4, 'free' => 2 ),
	),
	array(
		'category' => 'Local organizations & community groups',
		'org' => 'Greater Washington Black Chamber of Commerce',
		'url' => 'https://business.gwbcc.org/member-directory',
		'how_to' => 'Join and get listed in searchable directory.',
		'paid_free' => 'Paid',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 3, 'roi' => 3, 'ease' => 4, 'free' => 2 ),
	),
	array(
		'category' => 'Local organizations & community groups',
		'org' => 'Maryland Chamber of Commerce',
		'url' => 'https://www.mdchamber.org/',
		'how_to' => 'Join; statewide events and exposure.',
		'paid_free' => 'Paid',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 4, 'ease' => 4, 'free' => 2 ),
	),
	array(
		'category' => 'Local organizations & community groups',
		'org' => 'Northern Virginia Chamber of Commerce',
		'url' => 'https://web.nvcbusiness.org/search',
		'how_to' => 'Join; get directory listing and access to sponsorship/advertising.',
		'paid_free' => 'Paid',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 4, 'ease' => 4, 'free' => 2 ),
	),
	array(
		'category' => 'Local organizations & community groups',
		'org' => 'Central Maryland Chamber',
		'url' => 'https://web.centralmarylandchamber.org/search',
		'how_to' => 'Join; directory listing + sponsor recognition options.',
		'paid_free' => 'Paid',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 3, 'roi' => 3, 'ease' => 4, 'free' => 2 ),
	),
	array(
		'category' => 'Events & sponsorship opportunities',
		'org' => 'H Street Festival (DC)',
		'url' => 'https://hstreetfestival.org/partners',
		'how_to' => 'Become sponsor/vendor; sponsors acknowledged online.',
		'paid_free' => 'Paid',
		'priority' => 'High visibility / Medium effort',
		'notes' => 'Apply early; high demand',
		'scores' => array( 'authority' => 3, 'relevance' => 3, 'roi' => 2, 'ease' => 2, 'free' => 2 ),
	),
	array(
		'category' => 'Events & sponsorship opportunities',
		'org' => 'Adams Morgan Day (DC)',
		'url' => 'https://www.admoday.com/sponsorships-donations/',
		'how_to' => 'Sponsor or vendor; nonprofit tax-deductible options.',
		'paid_free' => 'Paid',
		'priority' => 'High visibility / Medium effort',
		'notes' => '',
		'scores' => array( 'authority' => 3, 'relevance' => 3, 'roi' => 2, 'ease' => 3, 'free' => 2 ),
	),
	array(
		'category' => 'Events & sponsorship opportunities',
		'org' => 'Arlington County Fair (VA)',
		'url' => 'https://arlingtoncountyfair.us/support-the-fair/',
		'how_to' => 'Sponsor packages with on-site presence + web mentions.',
		'paid_free' => 'Paid',
		'priority' => 'High visibility / Medium effort',
		'notes' => '',
		'scores' => array( 'authority' => 3, 'relevance' => 2, 'roi' => 2, 'ease' => 3, 'free' => 2 ),
	),
	array(
		'category' => 'Events & sponsorship opportunities',
		'org' => 'Montgomery County Agricultural Fair (MD)',
		'url' => 'https://mcagfair.com/sponsors/',
		'how_to' => 'Sponsor packages; sponsors listed on site.',
		'paid_free' => 'Paid',
		'priority' => 'High visibility / Medium effort',
		'notes' => '',
		'scores' => array( 'authority' => 3, 'relevance' => 2, 'roi' => 2, 'ease' => 3, 'free' => 2 ),
	),
	array(
		'category' => 'Events & sponsorship opportunities',
		'org' => 'Destination DC',
		'url' => 'https://washington.org/members/DC-information/sponsorship-opportunities',
		'how_to' => 'Sponsor citywide programs; includes digital mentions.',
		'paid_free' => 'Paid',
		'priority' => 'High visibility / Medium effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 3, 'roi' => 2, 'ease' => 3, 'free' => 2 ),
	),
	array(
		'category' => 'Events & sponsorship opportunities',
		'org' => 'Events DC',
		'url' => 'https://eventsdc.com/partner-us',
		'how_to' => 'Strategic partnerships; brand exposure around major events.',
		'paid_free' => 'Paid',
		'priority' => 'High visibility / Medium effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 3, 'roi' => 2, 'ease' => 3, 'free' => 2 ),
	),
	array(
		'category' => 'Local media outlets & publications',
		'org' => 'WTOP',
		'url' => 'https://wtop.com/advertise/',
		'how_to' => 'Buy ads or branded content features; strong DMV audience.',
		'paid_free' => 'Paid',
		'priority' => 'Media / Sponsored content',
		'notes' => 'Request 2025 media kit',
		'scores' => array( 'authority' => 5, 'relevance' => 3, 'roi' => 3, 'ease' => 2, 'free' => 3 ),
	),
	array(
		'category' => 'Local media outlets & publications',
		'org' => 'Greater Greater Washington',
		'url' => 'https://ggwash.org/advertise',
		'how_to' => 'Sponsor content; pitch urbanism/home-improvement angles.',
		'paid_free' => 'Paid',
		'priority' => 'Media / Sponsored content',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 3, 'roi' => 3, 'ease' => 3, 'free' => 3 ),
	),
	array(
		'category' => 'Local media outlets & publications',
		'org' => 'Washington Informer',
		'url' => 'https://www.washingtoninformer.com/washington-informer-media-kit/',
		'how_to' => 'Buy ads or advertorials; email on page.',
		'paid_free' => 'Paid',
		'priority' => 'Media / Sponsored content',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 3, 'roi' => 3, 'ease' => 3, 'free' => 3 ),
	),
	array(
		'category' => 'Local media outlets & publications',
		'org' => 'The Georgetowner',
		'url' => 'https://georgetowner.com/',
		'how_to' => 'Ad buys or sponsored articles.',
		'paid_free' => 'Paid',
		'priority' => 'Media / Sponsored content',
		'notes' => '',
		'scores' => array( 'authority' => 3, 'relevance' => 3, 'roi' => 2, 'ease' => 3, 'free' => 3 ),
	),
	array(
		'category' => 'Local media outlets & publications',
		'org' => 'Patch (DC/MD/VA)',
		'url' => 'https://patch.com/us/across-america/advertise-with-us',
		'how_to' => 'Buy local ads, sponsored posts, or create free directory listings.',
		'paid_free' => 'Mixed',
		'priority' => 'Media / Sponsored content',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 3, 'roi' => 3, 'ease' => 4, 'free' => 4 ),
	),
	array(
		'category' => 'Educational institutions & government pages',
		'org' => 'DC Government Vendor Portal',
		'url' => 'https://vendorportal.dc.gov/',
		'how_to' => 'Register as vendor to be eligible for listings/awards; searchable profile.',
		'paid_free' => 'Free',
		'priority' => 'High authority / Low effort',
		'notes' => 'Add NAICS and DUNS numbers',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 5, 'ease' => 3, 'free' => 5 ),
	),
	array(
		'category' => 'Educational institutions & government pages',
		'org' => 'DC Office of the CFO',
		'url' => 'https://cfo.dc.gov/service/vendor-services',
		'how_to' => 'Register via supplier portal; contact listed.',
		'paid_free' => 'Free',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 5, 'ease' => 3, 'free' => 5 ),
	),
	array(
		'category' => 'Educational institutions & government pages',
		'org' => 'Fairfax County Vendor Pitch Portal',
		'url' => 'https://www.fairfaxcounty.gov/procurement/vendor-pitch-portal',
		'how_to' => 'Submit one pitch reviewed by multiple county agencies + FCPS.',
		'paid_free' => 'Free',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 5, 'ease' => 3, 'free' => 5 ),
	),
	array(
		'category' => 'Educational institutions & government pages',
		'org' => 'Arlington County Supplier Portal',
		'url' => 'https://www.arlingtonva.us/Government/Departments/Management-and-Finance/Procurement/Vendor-Information',
		'how_to' => 'Register as supplier; used for bids and vendor records.',
		'paid_free' => 'Free',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 5, 'ease' => 3, 'free' => 5 ),
	),
	array(
		'category' => 'Educational institutions & government pages',
		'org' => 'Montgomery County Vendor Resources',
		'url' => 'https://www.montgomerycountymd.gov/vendor/',
		'how_to' => 'Register in vendor system; listed in public directory.',
		'paid_free' => 'Free',
		'priority' => 'High authority / Low effort',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 5, 'ease' => 3, 'free' => 5 ),
	),
	array(
		'category' => 'Educational institutions & government pages',
		'org' => 'DC Public Schools Partnerships',
		'url' => 'https://dcps.dc.gov/page/dcps-partners',
		'how_to' => 'Engage as partner or sponsor school initiatives.',
		'paid_free' => 'Paid/Free',
		'priority' => 'Community / High trust',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 5, 'ease' => 3, 'free' => 5 ),
	),
	array(
		'category' => 'Business directories & industry platforms',
		'org' => 'The Blue Book Network',
		'url' => 'https://www.thebluebook.com/',
		'how_to' => 'Claim or create company profile; get bid invites and directory exposure.',
		'paid_free' => 'Free/Paid',
		'priority' => 'Lead gen / High ROI',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 5, 'roi' => 4, 'ease' => 4, 'free' => 3 ),
	),
	array(
		'category' => 'Business directories & industry platforms',
		'org' => 'Houzz Pro Directory',
		'url' => 'https://www.houzz.com/pro',
		'how_to' => 'Create free Pro account; appear in drywall/painting searches.',
		'paid_free' => 'Free/Paid',
		'priority' => 'Lead gen / High ROI',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 4, 'ease' => 4, 'free' => 3 ),
	),
	array(
		'category' => 'Business directories & industry platforms',
		'org' => 'Angi (Angie’s List)',
		'url' => 'https://www.angi.com/pros',
		'how_to' => 'Set up free profile; paid options for leads.',
		'paid_free' => 'Free/Paid',
		'priority' => 'Lead gen / High ROI',
		'notes' => '',
		'scores' => array( 'authority' => 5, 'relevance' => 4, 'roi' => 4, 'ease' => 4, 'free' => 2 ),
	),
	array(
		'category' => 'Business directories & industry platforms',
		'org' => 'BuildZoom',
		'url' => 'https://www.buildzoom.com/',
		'how_to' => 'Claim profile; surfaces licensed contractors & past projects.',
		'paid_free' => 'Free/Paid',
		'priority' => 'Lead gen / High ROI',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 4, 'roi' => 3, 'ease' => 4, 'free' => 4 ),
	),
	array(
		'category' => 'Business directories & industry platforms',
		'org' => 'Porch',
		'url' => 'https://porch.com/',
		'how_to' => 'Join Pro Network; appear in local search results.',
		'paid_free' => 'Free/Paid',
		'priority' => 'Lead gen / High ROI',
		'notes' => '',
		'scores' => array( 'authority' => 4, 'relevance' => 4, 'roi' => 3, 'ease' => 4, 'free' => 4 ),
	),
);
